$(OUTPUT_DIR)/mod_fsdirectory.zip: mod_fsdirectory.php mod_fsdirectory.xml language/en-GB/mod_fsdirectory.ini language/en-GB/mod_fsdirectory.sys.ini tmpl/default.php Helper/FilesystemDirEntry.php Helper/FilesystemDirLister.php
	zip $(OUTPUT_DIR)/mod_fsdirectory.zip $^
